
version: build{build}
image: Visual Studio 2017
clone_folder: C:\CK-World\CK-Database-Projects\CK-Database
services: mssql2016
branches:
  only:
    - master
    - develop
environment:
  SqlServer/MasterConnectionString: Server=(local)\SQL2016;Database=master;User ID=sa;Password=Password12!
  CKSETUPREMOTESTORE_PUSH_API_KEY:
    secure: ffSyq7zhajO1GUXQraZnZiZGtrPjUMGXXhlS71JUDouxx43VgzbtRfqmZM6zKTmS
  CKSETUP_CAKE_TARGET_STORE_APIKEY_AND_URL:
    secure: ffSyq7zhajO1GUXQraZnZiZGtrPjUMGXXhlS71JUDos5aibfGQQ0zf4BWRjM02dn3zrvVnGZBp6bZwULB/ffASa7PO3mcKcqvppnG6eLYDU=
  CODECAKEBUILDER_SECRET_KEY:
    secure: ks+QpMhDl8xJnpAmU4OHdfh11TE+fwNBj4PvMAKrPGsJnNjXcKgXtgAyJo77SJBi
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
install: 'ps: ./CodeCakeBuilder/InstallCredentialProvider.ps1'
