# Basic appveyor configuration : CodeCakeBuilder does the job.
version: build{build}
services: mssql2012sp1
branches:
  only:
  - master
  - develop
environment:
  NUGET_API_KEY:
    secure: Cx0q/gQZQpP3eDf6H9lzIDpYYki+sGCpruxgDcFUJRoYdpH7l5aDh7afloH3uNLD
  MYGET_EXPLORE_API_KEY:
    secure: ZD+bH7GWRWC3hSiziFlXdMdV9X3uV1D9xlRwzLZ8jJwEqIMCA+HxKWobuf3WVBH6
  CK_DB_TEST_MASTER_CONNECTION_STRING:
    Server=(local)\SQL2012SP1;Database=master;User ID=sa;Password=Password12!
init:
- git config --global core.autocrlf true
install:
- ps: CodeCakeBuilder\Bootstrap.ps1
build_script:
- CodeCakeBuilder\bin\Release\CodeCakeBuilder.exe -nointeraction
test: off
